services:
  mysql:
    image: mysql:8.0
    container_name: systempos-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: systempos_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./systempos_db.sql:/docker-entrypoint-initdb.d/init.sql

  java-app:
    build: .
    container_name: systempos-java-app
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/systempos_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  mysql_data:
